version: "3.9"

services:
  app:
    build: .
    container_name: my_app
    restart: always
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: "production"
      DATABASE_URL: "${DATABASE_URL}"
      STRIPE_SECRET_KEY: "${STRIPE_SECRET_KEY}"

      # Firebase Config
      FIREBASE_API_KEY: "${FIREBASE_API_KEY}"
      FIREBASE_AUTH_DOMAIN: "${FIREBASE_AUTH_DOMAIN}"
      FIREBASE_PROJECT_ID: "${FIREBASE_PROJECT_ID}"
      FIREBASE_STORAGE_BUCKET: "${FIREBASE_STORAGE_BUCKET}"
      FIREBASE_MESSAGING_SENDER_ID: "${FIREBASE_MESSAGING_SENDER_ID}"
      FIREBASE_APP_ID: "${FIREBASE_APP_ID}"
      FIREBASE_MEASUREMENT_ID: "${FIREBASE_MEASUREMENT_ID}"
      SERVICE_ACCOUNT_PATH: "/usr/src/app/serviceAccount.json"

    volumes:
      - .:/usr/src/app
    command: npm run start
