name: Node.js CI

on:
  push:
    branches: ["main", "development", "T0-github-actions-testing-gates"]
  pull_request:
    branches: ["main", "development", "T0-github-actions-testing-gates"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Set environment variables
        run: echo "SERVICE_ACCOUNT_PATH=${{ secrets.SERVICE_ACCOUNT_PATH }}" >> $GITHUB_ENV

      - name: Run tests
        env:
          NODE_ENV: test
        run: npm test
