name: Node.js CI

on:
  push:
    branches: ["main", "development", "T0-github-actions-testing-gates"]
  pull_request:
    branches: ["main", "development", "T0-github-actions-testing-gates"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Create service account file
        run: |
          echo "${{ secrets.SERVICE_ACCOUNT_PATH }}" > serviceAccount.json
          echo "Content of serviceAccount.json:"
          cat serviceAccount.json
        shell: bash

      - name: Run tests
        env:
          NODE_ENV: test
          SERVICE_ACCOUNT_PATH: ./serviceAccount.json
        run: npm test
