name: Node.js CI

on:
  push:
    branches: ["main", "development"]
  pull_request:
    branches: ["main", "development"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run Subset Tests for Pull Requests
        if: ${{ github.event_name == 'pull_request' }}
        env:
          NODE_ENV: test
          SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
        run: |
          echo "Running tests with service account JSON from environment variable"
          npm run test:health && npm run test:models
        shell: bash
      - name: Run Full Test Suite on Merge
        if: ${{ github.event_name == 'push' }}
        env:
          NODE_ENV: test
          SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          JWT_SECRET: "af44eb058bc02fafcab3b069f7a9af2f04a9f0164e8a8c161c6c0fa5dc3d5ed15da851fb7279a1db84ec6ec1948069afcf2f07b124cbeebf46ec6957f1f9d05c"
        run: |
          echo "Running tests with service account JSON from environment variable"
          npm run test:all
        shell: bash
