name: Node.js CI

on:
  push:
    branches: ["main", "development", "T0-72-testing-gates"]
  pull_request:
    branches: ["main", "development"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run Subset Tests for Pull Requests
        if: ${{ github.event_name == 'pull_request' }}
        env:
          NODE_ENV: test
          SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
        run: |
          echo "Running tests with service account JSON from environment variable"
          npm run test:health && npm run test:models
        shell: bash
      - name: Run Full Test Suite on Merge
        if: ${{ github.event_name == 'push' }}
        env:
          NODE_ENV: test
          SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
        run: |
          echo "Running tests with service account JSON from environment variable"
          npm run test:all
        shell: bash
